FROM alpine:3.17.2
LABEL maintainer "DI GREGORIO Nicolas <nicolas.digregorio@gmail.com>"

ARG TRANSMISSION_VERSION='4.0.0'

### Environment variables
ENV LANG='en_US.UTF-8' \
    LANGUAGE='en_US.UTF-8' \
    TERM='xterm' \
    APPUSER='transmission' \
    APPUID='10003' \
    APPGID='10003' \
    TRANSMISSION_VERSION="${TRANSMISSION_VERSION}"

# Copy config files
COPY root/ /

### Install Application
RUN set -x && \
    chmod 1777 /tmp && \
    . /usr/local/bin/docker-entrypoint-functions.sh && \
    MYUSER=${APPUSER} && \
    MYUID=${APPUID} && \
    MYGID=${APPGID} && \
    ConfigureUser && \
    apk upgrade --no-cache && \
    apk add --no-cache --virtual=build-deps \
      autoconf \
      automake \
      bsd-compat-headers \
      cmake \
      curl-dev \
      curl \
      dbus-glib-dev \
      libdeflate-dev \
      gcc \
      g++ \
      gettext \
      intltool \
      libtool \
      libevent-dev \
      libnotify-dev \
      openssl-dev \
      patch \
      m4 \
      make \
      miniupnpc-dev \
      musl-dev \
    && \
    curl -SsL  https://github.com/transmission/transmission/releases/download/${TRANSMISSION_VERSION}/transmission-${TRANSMISSION_VERSION}.tar.xz -o /tmp/transmission.tar.xz && \
    tar xJf /tmp/transmission.tar.xz -C /tmp && \
    cd /tmp/transmission-* && \
    mkdir build && \
    cd build && \
    cmake \
      -DCMAKE_BUILD_TYPE=MinSizeRel \
      -DENABLE_DAEMON=ON \
      -DENABLE_QT=OFF \
      -DENABLE_UTILS=ON \
      -DENABLE_CLI=ON \
      -DENABLE_GTK=OFF \
      -DENABLE_MAC=OFF \
      -DCMAKE_INSTALL_PREFIX=/opt/transmission \
      -DCMAKE_INSTALL_LIBDIR=lib \
      -DBUILD_SHARED_LIBS=True \
      -DENABLE_TESTS=FALSE \
      -DWITH_SYSTEMD=FALSE \
      -DINSTALL_LIB=TRUE \
      .. \
    && \
    make -s && \
    make install && \
    curl -SsL https://github.com/Secretmapper/combustion/archive/release.zip -o /tmp/combustion.zip  && \
    unzip /tmp/combustion.zip -d /opt && \
    mkdir -p /tmp/twctemp && \
    TWCVERSION=$(curl -sX GET "https://api.github.com/repos/ronggang/transmission-web-control/releases/latest" \
	| awk '/tag_name/{print $4;exit}' FS='[""]') \
    && \
    curl -SsL https://github.com/ronggang/transmission-web-control/archive/${TWCVERSION}.tar.gz -o /tmp/twc.tar.gz && \
    tar xf /tmp/twc.tar.gz -C /tmp/twctemp --strip-components=1 && \
    mv /tmp/twctemp/src /opt/transmission-web-control && \
    mkdir -p /opt/kettu && \
    curl -SsL https://github.com/endor/kettu/archive/master.tar.gz -o /tmp/kettu.tar.gz && \
    tar xf /tmp/kettu.tar.gz -C /opt/kettu --strip-components=1 && \
    apk del --no-cache --purge \
      build-deps  \
    && \
    apk add --no-cache --virtual=run-deps \
      p7zip \
      bash \
      ca-certificates \
      jq \
      libcurl \
      libdeflate \
      libevent \
      libnotify \
      openssl \
      mailx \
      moreutils \
      miniupnpc \
      ssmtp \
      su-exec \
      unzip \
    && \
    mkdir -p /docker-entrypoint.d && \
    chmod +x /usr/local/bin/docker-entrypoint.sh && \
    ln -snf /usr/local/bin/docker-entrypoint.sh /docker-entrypoint.sh && \
    rm -rf /tmp/* \
           /var/cache/apk/*  \
           /var/tmp/*
    
### Volume
VOLUME ["/config","/downloads","/watch"]

### Expose ports
EXPOSE 9091 9092/tcp 9092/udp

### Running User: not used, managed by docker-entrypoint.sh
#USER transmission

### Start transmission
ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["transmission"]
